const AUDIT_ACTION = {
  CREATE: "CREATE",
  READ: "READ",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  SEARCH: "SEARCH",
  FILTER: "FILTER",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  ASSIGN: "ASSIGN",
  ACCEPT: "ACCEPT",
  REJECT: "REJECT",
  START: "START",
  COMPLETE: "COMPLETE",
  CONFIRM: "CONFIRM",
  CLOSE: "CLOSE",
  CANCEL: "CANCEL",
};

export default AUDIT_ACTION;
