const BOOKING_TIMELINE_EVENT = {
  CREATED: "CREATED",
  UPDATED: "UPDATED",
  CANCELLED: "CANCELLED",
  ASSIGNED: "ASSIGNED",
  REASSIGNED: "REASSIGNED",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  STARTED: "STARTED",
  COMPLETION_IMAGES_UPLOADED: "COMPLETION_IMAGES_UPLOADED",
  COMPLETED: "COMPLETED",
  CUSTOMER_CONFIRMED: "CUSTOMER_CONFIRMED",
  CLOSED: "CLOSED",
  ISSUE_IMAGES_UPLOADED: "ISSUE_IMAGES_UPLOADED",
};

export default BOOKING_TIMELINE_EVENT;
