const BOOKING_TIMELINE_EVENT = {
  CREATED: "CREATED",
  UPDATED: "UPDATED",
  CANCELLED: "CANCELLED",
  ASSIGNED: "ASSIGNED",
  REASSIGNED: "REASSIGNED",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  ARRIVING: "ARRIVING",
  STARTED: "STARTED",
  PAUSED: "PAUSED",
  RESUMED: "RESUMED",
  WORK_NOTE_ADDED: "WORK_NOTE_ADDED",
  COMPLETION_IMAGES_UPLOADED: "COMPLETION_IMAGES_UPLOADED",
  AWAITING_CONFIRMATION: "AWAITING_CONFIRMATION",
  COMPLETED: "COMPLETED",
  CUSTOMER_CONFIRMED: "CUSTOMER_CONFIRMED",
  CLOSED: "CLOSED",
  PAYMENT_CONFIRMED: "PAYMENT_CONFIRMED",
  ISSUE_IMAGES_UPLOADED: "ISSUE_IMAGES_UPLOADED",
};

export default BOOKING_TIMELINE_EVENT;
