const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
  MIN_LIMIT: 1,
  BATCH_MAX_REQUESTS: 10,
  CURSOR_DEFAULT_LIMIT: 20,
  CURSOR_MAX_LIMIT: 50,
};

export default PAGINATION;
